project:
  type: website
  output-dir: docs
  
website:
  title: "AK Sharma"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme:
      light: cosmo
      dark: solar
    css: styles.css
    toc: true



