project:
  type: website
  output-dir: docs
  
website:
  title: "AK Sharma"
  cookie-consent:
    type: express
    style: simple
    palette: light
  google-analytics: 
    tracking-id: "G-CLKLJ48B1Y"
    anonymize-ip: true
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: CV/Sharma_Resume_2024.pdf
        text: CV
      - text: Contact
        menu:
          - icon: linkedin
            text: LinkedIn
            href: https://www.linkedin.com/in/ashwinkr/
            target: _blank
          - icon: twitter
            text: (X) Twitter
            href: https://twitter.com/aksbioinfo
            target: _blank
          # - icon: bluesky
          #   text: Bluesky
          #   href: https://bsky.app/profile/compbio.bsky.social
          #  target: _blank
          - icon: envelope
            text: Email
            href: mailto:ashwinkr7@gmail.com
            
  page-footer: 
    background: dark
    left: © 2024 Ashwini Kumar Sharma
    right: This website is built with {{< fa heart title="a heart" >}}, [{{< fa brands github title="GitHub octocat logo" >}}](https://github.com/ashwini-kr-sharma/ashwini-kr-sharma.github.io){target=_blank}, [{{< fa brands r-project title="R Project" >}}](https://www.r-project.org/about.html){target=_blank} and [Quarto](https://quarto.org/){target=_blank}
            
format:
  html:
    theme:
      light: cosmo
      dark: solar
    css: styles.css
    toc: true



