project:
  type: website
  output-dir: docs
  
website:
  title: "AK Sharma"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - about.qmd
      - text: Contact
        menu:
          - icon: linkedin
            text: LinkedIn
            href: https://www.linkedin.com/in/ashwinkr/
            target: _blank
          - icon: twitter
            text: twitter
            href: https://twitter.com/aksbioinfo
            target: _blank
          # - icon: bluesky
          #   text: Bluesky
          #   href: https://bsky.app/profile/compbio.bsky.social
          #  target: _blank
          - icon: envelope
            text: email
            href: mailto:ashwinkr7@gmail.com
            
format:
  html:
    theme:
      light: cosmo
      dark: solar
    css: styles.css
    toc: true



